import { z } from 'zod';
import { find, type Blueprint } from './blueprints.js';

/** The chosen target architecture, persisted to .rnc/stack.json. */
export const Stack = z.object({
  frontend: z.string(),
  backend: z.string(),
  database: z.string(),
  /** 'none' for the golden Next.js monorepo (no docker); 'compose' otherwise. */
  runtime: z.enum(['none', 'compose']),
});
export type Stack = z.infer<typeof Stack>;

export interface Composed {
  stack: Stack;
  front: Blueprint;
  back: Blueprint;
  db: Blueprint;
  warnings: string[];
}

export class ComposeError extends Error {}

/**
 * Validate a front/back/db combo and resolve its blueprints. The golden path
 * (Next monorepo + SQLite) is the one combo that needs no container runtime.
 */
export function compose(sel: { frontend: string; backend: string; database: string }): Composed {
  const front = find(sel.frontend);
  const back = find(sel.backend);
  const db = find(sel.database);

  if (!front || front.kind !== 'frontend') throw new ComposeError(`unknown frontend '${sel.frontend}'`);
  if (!back || back.kind !== 'backend') throw new ComposeError(`unknown backend '${sel.backend}'`);
  if (!db || db.kind !== 'database') throw new ComposeError(`unknown database '${sel.database}'`);

  const warnings: string[] = [];

  // persistence adapter must exist for this backend×database pair
  if (back.persistence && !back.persistence.includes(db.id)) {
    throw new ComposeError(
      `no persistence adapter: ${back.label} has no support for ${db.label} ` +
        `(supported: ${back.persistence.join(', ')})`,
    );
  }

  const isGolden = front.id === 'next' && back.id === 'next-api' && db.id === 'sqlite';
  const runtime: Stack['runtime'] = isGolden ? 'none' : 'compose';

  if (runtime === 'compose') {
    warnings.push(`runtime polyglot → docker-compose será gerado (${3} serviços)`);
  }
  if (db.id === 'mongo' && back.migration?.mongo === 'none') {
    warnings.push(`${db.label}: sem migrations SQL — schema via document mapping`);
  }

  return { stack: { frontend: front.id, backend: back.id, database: db.id, runtime }, front, back, db, warnings };
}

/** Generate a docker-compose.yaml string from the composed blueprints. */
export function toCompose(c: Composed): string {
  if (c.stack.runtime === 'none') {
    throw new ComposeError('golden path (Next monorepo + SQLite) não usa docker-compose');
  }
  const { front, back, db } = c;
  const lines: string[] = [];
  lines.push('# Generated by rnc — do not edit by hand; re-run `rnc runtime up`.');
  lines.push('services:');

  // database
  lines.push(`  db:`);
  lines.push(`    image: ${db.image ?? 'postgres:17'}`);
  lines.push(`    environment:`);
  for (const e of db.env) lines.push(`      ${e}: \${${e}}`);
  if (db.volume) {
    lines.push(`    volumes:`);
    lines.push(`      - ${db.volume}`);
  }
  lines.push(`    healthcheck:`);
  lines.push(`      test: ["CMD-SHELL", "${db.health ?? 'true'}"]`);
  lines.push(`      interval: 5s`);
  lines.push(`      retries: 10`);

  // backend
  lines.push(`  backend:`);
  lines.push(`    build: ${back.compose?.build ?? './backend'}`);
  lines.push(`    environment:`);
  for (const e of back.env) lines.push(`      ${e}: \${${e}}`);
  lines.push(`    depends_on:`);
  lines.push(`      db:`);
  lines.push(`        condition: service_healthy`);
  if (back.port) lines.push(`    ports: ["${back.port}:${back.port}"]`);
  if (back.health) {
    lines.push(`    healthcheck:`);
    lines.push(`      test: ["CMD", "curl", "-f", "http://localhost:${back.port}${back.health}"]`);
    lines.push(`      interval: 5s`);
    lines.push(`      retries: 10`);
  }

  // frontend
  lines.push(`  frontend:`);
  lines.push(`    build: ${front.compose?.build ?? './frontend'}`);
  lines.push(`    depends_on:`);
  lines.push(`      backend:`);
  lines.push(`        condition: service_healthy`);
  if (front.port) lines.push(`    ports: ["${front.port}:${front.port}"]`);

  if (db.volume) {
    const vol = db.volume.split(':')[0];
    lines.push(`volumes:`);
    lines.push(`  ${vol}:`);
  }
  return lines.join('\n') + '\n';
}
